### PR TITLE
Remove scalariform, print full stack traces on test failures

### PR DESCRIPTION
**Pull request by ryan-williams**
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/guacamole/409)

### CODE REVIEW

**Comment by ryan-williams** [comment]
Actually while working on some of the other PRs I'm filing right now, Scalariform is screwing up my whitespace all over the place, I'm back on wanting to get rid of it :-\

**Comment by arahuja** [comment]
Yea, totally fine with getting rid of it - some kind of lint check might be nice though if there are alternatives

**Comment by ryan-williams** [comment]
Agreed. I'll look around tomorrow.

**Comment by timodonnell** [comment]
Yeah, agree that scaliform is annoying when it disagrees with intellij, but also agree that having some kind of linting enforcing style consistency is really nice. I wonder if there's a way to get it to agree with intellij better, or use some different linter that agrees better?

**Comment by ryan-williams** [comment]
I am theoretically in favor of linting but in practice our codebase does not obey un-disable-able scalariform rules in many places, resulting in a minefield of noise-changes that happen when you compile code. I find it to be a big pain and think we should remove it now and then think about a replacement.

[Here's what it just did to one of my branches](https://github.com/ryan-williams/guacamole/commit/77442c8f2731094f9b96290572508f32fe2a0c9b). I don't want any of those changes but afaik I can't make it stop doing that. The changes boil down to:
* imports: scalariform likes spaces inside each `{` and `}`. I actually slightly prefer this, but IntelliJ's "optimize imports" (⌘⇧O for me, idk if that's the default) can't be told to do it, and that functionality is *way* more important to me than the spacing nit.
* comment spacing: [one space before line comments](https://github.com/ryan-williams/guacamole/commit/77442c8f2731094f9b96290572508f32fe2a0c9b#diff-e5001cba3abbdfa83fc2a4489aa510ecR148), [removes intentional vertical alignment](https://github.com/ryan-williams/guacamole/commit/77442c8f2731094f9b96290572508f32fe2a0c9b#diff-23c169ad54dd125057edd0773d6a335eL41).
* scaladocs: [disagrees with Intellij](https://github.com/ryan-williams/guacamole/commit/77442c8f2731094f9b96290572508f32fe2a0c9b#diff-a5925f655fe562f03e4c20652341418bL163)

I'll look into e.g. [scalastyle](http://www.scalastyle.org/maven.html) next week, but I don't actually believe we're getting any benefit from this today and I'd like to just get rid of it as it's probably cost me tens of minutes in the last few days.

**Comment by timodonnell** [comment]
One kind of draconian approach would be do have travis fail if scalariform
changes anything when it is built. Then everyone just has to run
scalariform before doing a PR (probably good to run `mvn package` before
doing a PR anyway, and that's more convenient now with Ryan's test
speedups), so we no longer have the situation of running scalariform
affecting lots of files your PR had nothing to do with. I wouldn't be
opposed to this solution, but if consensus is better to just drop it then
that's fine with me too

**Comment by arahuja** [comment]
@timodonnell I think the problem with that is when intellij and scalariform keep fighting each other

**Comment by ryan-williams** [comment]
Yea, intellij vs. scalariform is bad. Scalariform also does things that intellij doesn't care about but that I do, and it can't be told to stop, afaik; some of my above examples are in each of these categories.

**Comment by ryan-williams** [comment]
[Here's](https://github.com/ryan-williams/guacamole/commit/118e080e57e285bfe9f4fa1a951b0dbd051463a0) another commit showing scalariform mangling my whitespace

**Comment by arahuja** [comment]
I'd say let's merge this in the meantime? Right now 11 files are re-formatted by scalariform on master, so every `mvn package` will wreck your branch.

**Comment by ryan-williams** [comment]
Yea, that's my bad for getting ahead of this disabling and throwing out scalariform changes in the other PRs I merged in. Sorry about that.

**Comment by arahuja** [comment]
thanks @ryan-williams!

**Pull request merged**
