### PR TITLE
Add padding to somatic test files

### PR DESCRIPTION
**Pull request by arahuja**
This PR has two pieces:
1. Expand the `cancer-wgs` test files to have a 180 base window around them
2. Update `GeneratePartialFasta` to also include a larger window in the reference.

@timodonnell This results in one failing test on "call germline variants" where the second entry is there is not a true germline variant when you include all of the reads that cover it. I could replace it with another, but I'm not sure I can find one that also fails the strand bias filter - any ideas?

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/guacamole/479)

### CODE REVIEW

**Comment by ryan-williams** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[scripts/generate-partial-fasta-for-tests, line 41 \[r1\]](https://reviewable.io:443/reviews/hammerlab/guacamole/479#-KI4TP1I_gD3_LQ_QCsp:-KI4TP1J_Kf92C50l1eB:-1937429046) ([raw file](https://github.com/hammerlab/guacamole/blob/49ed54ec161d03ad3bcdf7145163fbd13c07de35/scripts/generate-partial-fasta-for-tests#L41)):*
> ```
> 
> # HG19 reference
> time java -Xmx4g -XX:MaxPermSize=512m "-Dspark.master=local[1]" -cp "$full_jar" "$MAIN_CLASS" \
> ```

anything noteworthy about this change?

---

*[scripts/generate-partial-fasta-for-tests, line 44 \[r1\]](https://reviewable.io:443/reviews/hammerlab/guacamole/479#-KI4T770_0MnsPsMJt2w:-KI4T770_0MnsPsMJt2x:803764819) ([raw file](https://github.com/hammerlab/guacamole/blob/49ed54ec161d03ad3bcdf7145163fbd13c07de35/scripts/generate-partial-fasta-for-tests#L44)):*
> ```
>     --reference-fasta "$HG19_FULL_FASTA_PATH" \
>     --output src/test/resources/hg19.partial.fasta \
> 	--bam-reader-api hadoopbam \
> ```

spaces vs tabs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hammerlab/guacamole/479)*

**Comment by arahuja** [comment]
*[scripts/generate-partial-fasta-for-tests, line 41 \[r1\]](https://reviewable.io:443/reviews/hammerlab/guacamole/479#-KI4TP1I_gD3_LQ_QCsp:-KI4VGjcHW3TBkArskhK:-1194412185) ([raw file](https://github.com/hammerlab/guacamole/blob/49ed54ec161d03ad3bcdf7145163fbd13c07de35/scripts/generate-partial-fasta-for-tests#L41)):*
<details><summary><i>Previously, ryan-williams (Ryan Williams) wrote…</i></summary>
> anything noteworthy about this change?
</details>
ah no, just leftover from updating this on my machine. good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hammerlab/guacamole/479)*

**Comment by timodonnell** [comment]
I'd be fine just commenting out the germline test for now to get this PR in. I can look into making it a correct test at a later point

**Comment by arahuja** [comment]
> I'd be fine just commenting out the germline test for now to get this PR in. I can look into making it a correct test at a later point

Cool, I'll do that for now @timodonnell

**Pull request merged**
