### PR TITLE
Add joint caller

### PR DESCRIPTION
**Pull request by timodonnell**
This PR starts a germline and somatic multisample variant caller. There is much more to do but it's overdue for me to get some feedback on this and got it integrated into master.

What's implemented:
 * Call germline and somatic variants using a likelihood ratio test on individual samples and pooled reads, including indels
 * Write out single-sample and multisample VCFs for all calls across all samples with diagnostic info
 * Simple unit tests as well as an integration test that runs it on a subset of a real dataset

What is left to do
 * Filters (strand bias, evidence in normal, homopolymers, etc.)
 * Phasing of variants, including an idea to get better sensitivity from phasing somatic variants with germline hets
 * Support for RNA

Outstanding issues
 * Travis still dies while running the integration test. I think it may be running too slowly do to scoverage? Help welcome on this.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/guacamole/384)

### CODE REVIEW

**Comment by timodonnell** [comment]
I tried disabling scoverage. The travis build still fails, but it looks like it's just non-specifically running out of memory while running the tests (apparently they all run in the same jvm?) The OOM error hit during the `StructuralVariantCaller` tests this time. When I up to the memory used for the tests in the `pom.xml` file to 4gb, it seems like travis [kills](https://travis-ci.org/hammerlab/guacamole/builds/109426849) the build. When it's at 2gb then we get a java out of memory error much sooner. It's at 3gb now. Anyone know of a way to get each test suite to run in a fresh jvm, or have other ideas? (Can we just bump the memory available on the travis VM somehow?)

**Comment by timodonnell** [comment]
Well I dropped the `StructuralVariantCaller` and now the travis build is working. I don't think this is the fault of `StructuralVariantCaller` per se but I am not totally sure; I have not dug into its tests.

@arahuja and I were actually talking about cleaning up the Guacamole code base and considering dropping callers that are not actively maintained / headed toward production use, such as this one. Having things like this around is nice as a foundation for someone later to build from but discourages changing the Guacamole code base since lots of random stuff starts failing in these other callers. Maybe we should just go ahead with it, knowing that we can get it back from history if anyone wants to develop an SV caller at some point.

**Comment by ryan-williams** [comment]
I am generally "pro" aggressively deleting things that can be recalled from history later, fwiw

**Comment by timodonnell** [comment]
Issues raised during in-person code review:
 * Need to include VAF, allelic depths, and triggered fields for normal samples in VCF
 * Need to filter somatic calls by germline evidence (not going to fix this in this PR, will fix later as part of filters)
 * Change generate-partial-fasta to be run directly from the jar instead of as a (user-facing) Guacamole subcommand
 * Get rid of URL parsing hairiness

@arahuja @ryan-williams @e5c please let me know if there were any other issues I forgot. Thanks for the feedback!

**Comment by timodonnell** [comment]
Updated to address feedback
 * Added VAF and allelic depths for normal samples. Decided not to write out a TRIGGERED field for normal samples since currently we only call germline variants using the pooled data, so a per-sample field is not meaningful.
 * The filtering somatic calls by germline evidence will be pushed to #385 
 * `generate-partial-fasta` now runs as its own top-level command
 * URL parsing has been replaced with the `--tissue-types`, `--analytes`, and `--sample-names` commandline arguments
 * Added some very simple tests for `PileupStats`. Fixed an edge case involving SNVs immediately preceding insertions.
 * We now only `.collect` and output a single variant at each locus. Will be interesting to see if this resolves the memory issues running on real data.

**Comment by timodonnell** [comment]
Think I'll merge this unless @e5c @arahuja @ryan-williams have any other suggestions

**Comment by arahuja** [comment]
I left a few comments on things. It'd be nice to have some tests for all the `*AlleleEvidence` classes or `PileupStats`

---

Reviewed 44 of 62 files at r1, 6 of 15 files at r2, 5 of 5 files at r3, 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[pom.xml, line 399 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApMci3nUNfxJV6Jkoi:-KApMci4EObh1odAftbQ:-205175450) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/pom.xml#L399)):*
Did you want to comment this out or just remove it?

---

*[README.md, line 55 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApH8FpKpE1yhTJmXmN:-KApH8Fq8MXRJ11YaX6J:-247602196) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/README.md#L55)):*
Might be worth putting a different example, rather than the test case one which is different from how someone would run it?

---

*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/ReadSubsequence.scala, line 40 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApNXFj5sA6kPLU6FUd:-KApNXFj5sA6kPLU6FUe:1590640127) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/ReadSubsequence.scala#L40)):*
Does this ever happen, is there a reason for the default of 10?

---

*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCaller.scala, line 17 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApOxEQoqq6UT0aRG2_:-KApOxEQoqq6UT0aRG2a:-981911377) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCaller.scala#L17)):*
What is the difference between this parameter and the last? Are they mutually exclusive?

---

*[src/main/scala/org/hammerlab/guacamole/Common.scala, line 258 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApIwFMNiMiucNG7ZQK:-KApIwFNwBD7rq3R8TS1:957872069) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/Common.scala#L258)):*
Is there a reason to special case loci here? Is that a common file extension?

---

*[src/main/scala/org/hammerlab/guacamole/Common.scala, line 279 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApJMBHH3ayFsaSh2TN:-KApJMBHH3ayFsaSh2TO:-241270421) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/Common.scala#L279)):*
Is there a specific use-case for this as opposed to using one of the functions above directly?

---

*[src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala, line 25 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApHyrbW2rJ6a5Mn6iO:-KApHyrbW2rJ6a5Mn6iP:63989183) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala#L25)):*
spelling

---

*[src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala, line 32 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApHy1aqpzCXNHYdqD_:-KApHy1bCI47FF7nUT_o:63989183) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala#L32)):*
spelling

---

*[src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala, line 40 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApIFwrL-G-X00XAaVG:-KApIFwrL-G-X00XAaVH:-898201630) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala#L40)):*
What does this do?

---

*[src/main/scala/org/hammerlab/guacamole/LociSet.scala, line 170 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApJrE6kelZGeX3P_rT:-KApJrE6kelZGeX3P_rU:705043261) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/LociSet.scala#L170)):*
Worth documenting this case of none? When would this come up?

---

*[src/main/scala/org/hammerlab/guacamole/reads/MappedRead.scala, line 37 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApJaWGWCntjvXrU9iU:-KApJaWGWCntjvXrU9iV:-1320504018) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/reads/MappedRead.scala#L37)):*
Are the read names used somewhere now? Is there a reason to hang out to these? They are usually fairly long/big right?

---

*[src/main/scala/org/hammerlab/guacamole/reads/Read.scala, line 416 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApKGvQc7VMt0Nj4Int:-KApKGvR0cZkr1BUJAy1:-2080230836) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/reads/Read.scala#L416)):*
OOC, a reason to record this?

---

*[src/test/resources/cancer-wgs1/igv_session.xml, line 1 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApKhlS3AYfIRI__VWR:-KApKhlS3AYfIRI__VWS:965600577) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/resources/cancer-wgs1/igv_session.xml#L1)):*
Should this be in the commit?

---

*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala, line 22 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLFbPSWRgaiHF_mnd:-KApLFbPSWRgaiHF_mne:1442943794) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala#L22)):*
I don't think there are any tests here? Can this just be a separate app/main/command that runs?

---

*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala, line 124 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLQg7TgTeTfH9iFQG:-KApLQg7TgTeTfH9iFQH:761732955) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala#L124)):*
Since we are checking in the test file here, can we just check it in with the coordinates updates? Would be easier than debugging this could at some point or easy comparison is someone is looking at the data files?

---

*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala, line 187 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLcu8CwyAmUmzvOv3:-KApLcu9Y9OFhdmF4qfw:-2077986060) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala#L187)):*
This seems generally useful - worth moving to it's own file, and adding some tests?

---

*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerSuite.scala, line 20 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApK_oWs9hM5_QCcXu4:-KApK_oWs9hM5_QCcXu5:1290039908) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerSuite.scala#L20)):*
Worth moving these tests into a `ReadSubsequenceSuite`?

---

*[src/test/scala/org/hammerlab/guacamole/util/TestUtil.scala, line 174 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApMKlUnjvv5C4H-ibq:-KApMKlUnjvv5C4H-ibr:-1501851689) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/util/TestUtil.scala#L174)):*
Was there a reason for this change? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-:-KApPvlimHViXQ-KNrMx:72751192)*

**Comment by timodonnell** [comment]
*[pom.xml, line 399 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApMci3nUNfxJV6Jkoi:-KApXH1cK1wo8W2AwK7n:370111202) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/pom.xml#L399)):*
I think let's leave it commented out so we can add it back easily?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[README.md, line 55 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApH8FpKpE1yhTJmXmN:-KApaC3qwIvvWYN6xjUl:396548341) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/README.md#L55)):*
Good call, updated README to instead give a run using the synth1 dataset

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/ReadSubsequence.scala, line 40 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApNXFj5sA6kPLU6FUd:-KApauDReEtTwCGTV_GC:1480923823) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/ReadSubsequence.scala#L40)):*
I'll get rid of this. I was hitting an issue where the `Byte` was silently overflowing into negative numbers but with that fixed it shouldn't happen

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCaller.scala, line 17 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApOxEQoqq6UT0aRG2_:-KApbXkKPXh2CSp20SfA:-142940540) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCaller.scala#L17)):*
The out dir option gives a directory with a VCF per sample, whereas the --out option gives a single multisample VCF. They are not mututally exclusive. I added the out dir option because varcode doesn't support multisample VCFs. Is there a clearer way I could word this?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/Common.scala, line 258 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApIwFMNiMiucNG7ZQK:-KApc-DSh91kg7gkOyPJ:-1378923440) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/Common.scala#L258)):*
Nope, just made it up. I feel like having a descriptive extension for that particular format (which we also made up ) makes sense. I could drop the `.txt` part though if that's better you think

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by ryan-williams** [comment]
*[pom.xml, line 399 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApMci3nUNfxJV6Jkoi:-KApdy7693uYkk93DTKQ:-1433146522) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/pom.xml#L399)):*
/vote remove it, get it from history if we want it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/Common.scala, line 279 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApJMBHH3ayFsaSh2TN:-KApeJ-IdHuXe14hGduJ:561775888) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/Common.scala#L279)):*
Yeah, I needed it to load the force call loci in the joint caller. Want to use the same logic for `--force-call-loci` as `--loci` but different argument names

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala, line 40 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApIFwrL-G-X00XAaVG:-KApfP40yEUCUoSiRXA0:1942312841) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/filters/FishersExactTest.scala#L40)):*
This method turned out to be unused, deleted it. It was something like p value of k heads in n coin flips

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/LociSet.scala, line 170 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApJrE6kelZGeX3P_rT:-KApf_aH-aT_VICB1Tef:-279216309) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/LociSet.scala#L170)):*
Just needed it for the `--force-call-loci` stuff, where "don't force call anything" is the default. Added a comment

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/reads/MappedRead.scala, line 37 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApJaWGWCntjvXrU9iU:-KApfxa5JhGhnr6AQndP:1201101360) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/reads/MappedRead.scala#L37)):*
Going to need them for phasing later. At some point we may want to have a way to load only the read properties needed by the particular caller, but that is a substantial project. I'd rather leave them in since we're going to want them later, although it's definitely true there is a memory footprint

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/reads/Read.scala, line 416 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApKGvQc7VMt0Nj4Int:-KApgjiKwIKPK564mBbh:-709049041) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/main/scala/org/hammerlab/guacamole/reads/Read.scala#L416)):*
was debugging some slow stuff and it seemed useful to be really clear about when the index is being used and if not why

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/test/resources/cancer-wgs1/igv_session.xml, line 1 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApKhlS3AYfIRI__VWR:-KApgt8Xr2Z1PdLtLUqk:239045359) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/resources/cancer-wgs1/igv_session.xml#L1)):*
I suppose not, I'll remove it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala, line 22 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLFbPSWRgaiHF_mnd:-KAph7W0SIvOPydb7xpt:190401389) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala#L22)):*
My thought it that later we will want to assert that the sensitivity / specificity is > some value. It also does test that the caller doesn't crash, which has caught quite a few things. I think having it run as a test is useful

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala, line 124 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLQg7TgTeTfH9iFQG:-KAphz-_W65n30qDGD4H:-1567409710) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala#L124)):*
You mean just change the csv to be inclusive rather than interbase coordinates? Could do that, but I'm kind of using the existing format as a standard for varlens output and input, so it seems reasonable to stay compatible with varlens

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[pom.xml, line 399 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApMci3nUNfxJV6Jkoi:-KApjTLvdnWIeFtdkhgg:1864903132) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/pom.xml#L399)):*
ok, I'll delete all scoverage stuff in the pom

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerSuite.scala, line 20 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApK_oWs9hM5_QCcXu4:-KAptTgWJzuDJsWATjAh:218573789) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerSuite.scala#L20)):*
Sure, I'll break all of these tests out into separate files based on what they test, and move them into a `jointcaller` package

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/test/scala/org/hammerlab/guacamole/util/TestUtil.scala, line 174 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApMKlUnjvv5C4H-ibq:-KApuAdu3bKjYFFHyVkr:-1817477972) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/util/TestUtil.scala#L174)):*
Yeah, in `TestUti.loadReads` we call this function, but there are cases where we already have the full path resolved. This change lets us call `TestUtil.loadReads` and `TestUtil.loadPileup` on both already resolved absolute paths and on paths relative to the test data

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala, line 187 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLcu8CwyAmUmzvOv3:-KAq2gSRnit5DnGhTHVf:1297468246) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/SomaticJointCallerIntegrationTests.scala#L187)):*
Sure, I'll factor it out

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
Just pushed fixes for most of Arun's comments, except for the general request for more tests, which I'm going to take a stab at now

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-:-KAq3OK1BqhJak0mjnVN:64562397)*

**Comment by timodonnell** [comment]
Pushed a bunch of changes to address feedback (thanks!) and also:
 * Fixed a bug that had us calling variants at sites where the reference is N
 * Fixed a similar bug that was calling variants when the reads have an N
 * Made a substantial simplification to how deletions are handled: we now call them directly as VCF-style variants (`alt.length == 1, e.g. ACACA>A`) instead of `CACA > .` This allowed me to remove all the `transformAlleles` methods
 * Fixed a bug in the integration test that was giving the wrong force call loci for deletions
 * Added a few more assertions to `PileupStatsSuite`. I think the `AlleleEvidence` classes are thin enough to go without dedicated tests for now.

Please let me know if anyone has more feedback or looks good to merge

**Comment by timodonnell** [comment]
@e5c I was worried that some complex regions of the genome may be generating huge numbers of alleles (and thus generating variants with a big memory footprint for the allelic depth field), so I just pushed a change that adds a `--max-alleles-per-site` option (default=4). Worth giving this one a shot if you are still hitting memory issues on the cluster.

**Comment by e5c** [comment]
@timodonnell Cool I'll give it a shot thanks!

**Comment by arahuja** [comment]
Reviewed 6 of 14 files at r6, 1 of 1 files at r7, 12 of 16 files at r8, 5 of 5 files at r9.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[README.md, line 56 \[r9\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KBLH9QH-UHILFShae_9:-KBLH9QIkBje-rwwUFAR:794142894) ([raw file](https://github.com/hammerlab/guacamole/blob/02008344365f326072373a50947ee82c7d542d21/README.md#L56)):*
Worth including this? Maybe just put the specs? 

---

*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/AlleleAtLocus.scala, line 140 \[r9\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KBLIMDjJu1AQf7mw8_m:-KBLIMDjJu1AQf7mw8_n:1892364380) ([raw file](https://github.com/hammerlab/guacamole/blob/02008344365f326072373a50947ee82c7d542d21/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/AlleleAtLocus.scala#L140)):*
This will throw an error if `maxAlleles` is not greater than 0? Worth reporting something about this? Or why would this happen. Maybe return result if the value is not > 0?

---

*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/NormalDNASampleAlleleEvidence.scala, line 42 \[r9\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KBLIdC4QQiP7wKtUKaY:-KBLIdC4QQiP7wKtUKaZ:96104794) ([raw file](https://github.com/hammerlab/guacamole/blob/02008344365f326072373a50947ee82c7d542d21/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/NormalDNASampleAlleleEvidence.scala#L42)):*
nit: Is the `_` necessary?

---

*[src/test/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCallerIntegrationTests.scala, line 124 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLQg7TgTeTfH9iFQG:-KBLKlfQpedemgRafxnf:-648457693) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCallerIntegrationTests.scala#L124)):*
Yea I meant just adjusting the data once and saving it that way. I think that'd be easier to compare with the file directly rather having to debug through this transformation if anything else went wrong? Doesn't seem like we need the additional dependency/transformation?

---

*[src/test/scala/org/hammerlab/guacamole/util/VCFComparison.scala, line 27 \[r9\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KBLJxQzvL_vY87gwQ0Y:-KBLJxQzvL_vY87gwQ0Z:388634675) ([raw file](https://github.com/hammerlab/guacamole/blob/02008344365f326072373a50947ee82c7d542d21/src/test/scala/org/hammerlab/guacamole/util/VCFComparison.scala#L27)):*
Remove these?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by arahuja** [comment]
@timodonnell Went through it once again, things look good - left some comments, but feel free to use or ignore.

Thanks!

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/AlleleAtLocus.scala, line 140 \[r9\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KBLIMDjJu1AQf7mw8_m:-KBPQrB_okx0aTJpC7Jn:-1881718866) ([raw file](https://github.com/hammerlab/guacamole/blob/02008344365f326072373a50947ee82c7d542d21/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/AlleleAtLocus.scala#L140)):*
maxAlleles is just a convenience parameter where the caller can ask to only have at most a certain number of alleles returned. It really isn't meaningful for this to be 0 -- there would be no point in calling this method

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/main/scala/org/hammerlab/guacamole/commands/jointcaller/NormalDNASampleAlleleEvidence.scala, line 42 \[r9\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KBLIdC4QQiP7wKtUKaY:-KBPRBKWIzJ2hbvsce4Y:449177819) ([raw file](https://github.com/hammerlab/guacamole/blob/02008344365f326072373a50947ee82c7d542d21/src/main/scala/org/hammerlab/guacamole/commands/jointcaller/NormalDNASampleAlleleEvidence.scala#L42)):*
nope, you're right!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
*[src/test/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCallerIntegrationTests.scala, line 124 \[r5\]](https://reviewable.io:443/reviews/hammerlab/guacamole/384#-KApLQg7TgTeTfH9iFQG:-KBPRIOn3hVkA8lxRdHV:-2057152387) ([raw file](https://github.com/hammerlab/guacamole/blob/7e8c792e31d88a477181712e4b92d21f4da59f80/src/test/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCallerIntegrationTests.scala#L124)):*
Yeah, it's definitely a reasonable point. In the spirit of being able to easily incorporate other data generated by varlens though, I think I'll leave this as is for now

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/384)*

**Comment by timodonnell** [comment]
Thanks for all the feedback @arahuja @ryan-williams and @e5c , lots of good improvements. I just pushed some very small tweaks to address the @arahuja 's review, and plan to merge this once the travis tests have succeeded

**Pull request merged**
