### PR TITLE
No more mdtagging

### PR DESCRIPTION
**Pull request by timodonnell**
This is my WIP on removing md tagging and making `ReferenceBroadcast` the standard way of getting a reference. Making a PR in case people have comments on the overall approach. Still working on some failing tests.

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/guacamole/398)

### CODE REVIEW

**Comment by timodonnell** [comment]
Ok, I think this is all set. All tests run now. 

I also fixed an issue in the test file `different_start_reads.sam` that had inconsistent CIGAR strings and read sequences.

Thanks for bearing with me on the size of this PR.

**Comment by arahuja** [comment]
Most things look good here. I didn't give as close a pass to the tests. One high-level question would be at what point we do use the broadcast vs just the sequences.

I've had a mental model of keeping Spark things in `DistributedUtil` and the `Callers` and keeping `Read` and `Pileup` unaware to Spark. What do you think of that?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-:-KDdkBSZsyNT-7B6yDsy:-1033200165)*

**Comment by timodonnell** [comment]
Agreed, that's been my mental model too. I think we're still adhering to it since `Pileup` has a `ContigSequence` which is a trait that's just a way to take slices of a contig. The implementation of that trait uses Spark but conceptually it's not spark-specific.

---

Review status: 0 of 55 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-:-KDe0XuRPIkdRZWKhyNY:-1890050456)*

**Comment by ryan-williams** [comment]
love all the deleted code. left a couple comments. i don't love making all those tests instantiate all the spark machinery but it's fine, i can take on changing that.

---

Review status: 0 of 55 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/generate-partial-fasta-for-tests, line 10 \[r1\]](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-KDeDHoTMkHed9k7eZ0K:-KDeDHoTMkHed9k7eZ0L:1555233183) ([raw file](https://github.com/hammerlab/guacamole/blob/196006d3ffb45bb6aadae4702a5c74ac347bd737/scripts/generate-partial-fasta-for-tests#L10)):*
feels weird to be committing paths in your homedir. possible alternative: stub to `wget` from a URL with override based on an env var that user can set.

---

*[src/test/scala/org/hammerlab/guacamole/reads/ReadSetSuite.scala, line 68 \[r1\]](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-KDeJxa_iIIZM1EjUt70:-KDeJxa_iIIZM1EjUt71:-1898210825) ([raw file](https://github.com/hammerlab/guacamole/blob/196006d3ffb45bb6aadae4702a5c74ac347bd737/src/test/scala/org/hammerlab/guacamole/reads/ReadSetSuite.scala#L68)):*
if we're keeping this case we should at least document why it's here and commented

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-:-KDeKDsEljEcOuN_G7du:1018150488)*

**Comment by timodonnell** [comment]
Great thanks for the reviews Arun and Ryan. Pushing a fix for these issues momentarily

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-:-KDeZmbOoMhcnzB4alez:1224015760)*

**Comment by timodonnell** [comment]
Review status: 0 of 55 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/generate-partial-fasta-for-tests, line 10 \[r1\]](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-KDeDHoTMkHed9k7eZ0K:-KDeUY4aYq8GQKAjsKkp:786436964) ([raw file](https://github.com/hammerlab/guacamole/blob/196006d3ffb45bb6aadae4702a5c74ac347bd737/scripts/generate-partial-fasta-for-tests#L10)):*
Yeah, good catch. I'll just switch these to generic placeholders paths like `/path/to/hg19.fasta` for now

---

*[src/test/scala/org/hammerlab/guacamole/reads/ReadSetSuite.scala, line 68 \[r1\]](https://reviewable.io:443/reviews/hammerlab/guacamole/398#-KDeJxa_iIIZM1EjUt70:-KDeZhxCiDAoylayna5q:32887432) ([raw file](https://github.com/hammerlab/guacamole/blob/196006d3ffb45bb6aadae4702a5c74ac347bd737/src/test/scala/org/hammerlab/guacamole/reads/ReadSetSuite.scala#L68)):*
oh good catch! I didn't mean to leave these commented out

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/guacamole/398)*

**Comment by timodonnell** [comment]
Updated to address comments and also rename `referenceGenome` to `reference` in a few places for consistency. Once the travis tests run this should be good to merge

**Pull request merged**
