### PR TITLE
remove unused reference parameters

### PR DESCRIPTION
**Pull request by ryan-williams**
turns out there were many of these laying around

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/guacamole/415)

### CODE REVIEW

**Comment by ryan-williams** [comment]
heh I just remembered this overlaps with #401. I think this one does more though. I'm happy to rebase this on that though if we merge it first.

**Comment by timodonnell** [comment]
Delaying review of this one for the reason you noted

**Comment by ryan-williams** [comment]
I updated this one so it's ready for review.

**Comment by timodonnell** [comment]
LGTM

**Pull request merged**
